name: llama-finetune
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch>=2.2.0
      - transformers>=4.44.0
      - datasets
      - accelerate
      - peft
      - safetensors
      - sentencepiece
# Note: bitsandbytes is CUDA-only and not required on Apple Silicon. Install it optionally on Linux/NVIDIA.
